apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-jobmanager
  labels:
    app: flink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink
      role: jobmanager
  template:
    metadata:
      labels:
        app: flink
        role: jobmanager
    spec:
      containers:
      - name: flink
        image: paul8263/flink-1.9.2:1.9.2
        args: ["jobmanager"]
        ports:
        - name: web-port
          containerPort: 8081
        volumeMounts:
        - name: flink-config-volume
          mountPath: /flink-1.9.2/conf
      volumes:
        - name: flink-config-volume
          configMap:
            name: flink-config
