apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-taskmanager
  labels:
    app: flink
    role: taskmanager
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flink
  template:
    metadata:
      labels:
        app: flink
    spec:
      containers:
      - name: flink
        image: paul8263/flink-1.9.2:1.9.2
        args: ["taskmanager"]
        ports:
        - name: web-port
          containerPort: 8081
        volumeMounts:
        - name: flink-config-volume
          mountPath: /flink-1.9.2/conf
      volumes:
        - name: flink-config-volume
          configMap:
            name: flink-config
